Script started on Tue 26 Nov 2013 04:41:16 PM PST
[tho36@hills ~]$ # ***** ASMT03 *****
[tho36@hills ~]$ # Thuong Ho
[tho36@hills ~]$ date
Tue Nov 26 16:41:48 PST 2013
[tho36@hills ~]$ pwd
/students/tho36
[tho36@hills ~]$ id
uid=27302(tho36) gid=590(b20137) groups=590(b20137),7025(c71768),7097(c74418),7107(c74686),7109(c74688)
[tho36@hills ~]$ 
[tho36@hills ~]$ chmod 100 Managers 
[tho36@hills ~]$ ./newmanager
Welcome! Let me check if the Manager file is available.
Ok checking permissions now...
newmanager: Oh dear, looks like you don't have both read and write permissions to Manager!
[tho36@hills ~]$ rm Managers 
rm: remove write-protected regular file `Managers'? yes
[tho36@hills ~]$ ./newmanager
Welcome! Let me check if the Manager file is available.
Oops! Manager file is not in current directory. Let me copy if from Source...
Ok checking permissions now...
Looks like everything checks out ok!

***** You can type EXIT anytime to end the program. *****

Please enter the Department number: 5
Please enter the Department name: Dr. Who       Mystery Finder              Unsolved Mystery ies
Please enter the Manager's name: Dr. Who
Please enter the Manager's employee ID: b
newmanager: b is not a number
Please enter the Manager's employee ID: 5b
newmanager: 5b is not a number
Please enter the Manager's employee ID: 100

Here is the updated Managers file:
Jane Scientist:14:1:Research and Development
Charlie Ceo:1:3:Office of the President
Sally Sliderule:622:4:Engineering
Dr. Who:100:5:Unsolved Mysteries
Lawrence Friendly:833:7:Administration
Joe Worker:489:14:Manufacturing
Mary Money:893:17:Payroll
Mary Mailwoman:17:45:Shipping and Receiving
Mr. Ed:5:50:Health
Jeri Juntz:552:77:Maintenance
Sammy Screw:78:98:Assembly
Joe Piscipo:4532:200:Quality Assurance

Add another entry or type EXIT to end the program.
Please enter the Department number: 3 b
newmanager: b is not a number
Please enter the Department number: 3 5
Dr. Who:100:5:Unsolved Mysteries
Dept 5 already exist, overwrite?n
Add another entry or type EXIT to end the program.
Please enter the Department number: 5 7 5
Dr. Who:100:5:Unsolved Mysteries
Dept 5 already exist, overwrite?y
Please enter the Department name: Mystery Machine
Please enter the Manager's name: Scooby Doo
Please enter the Manager's employee ID: 123

Here is the updated Managers file:
Jane Scientist:14:1:Research and Development
Charlie Ceo:1:3:Office of the President
Sally Sliderule:622:4:Engineering
Scooby Doo:123:5:Mystery Machine
Lawrence Friendly:833:7:Administration
Joe Worker:489:14:Manufacturing
Mary Money:893:17:Payroll
Mary Mailwoman:17:45:Shipping and Receiving
Mr. Ed:5:50:Health
Jeri Juntz:552:77:Maintenance
Sammy Screw:78:98:Assembly
Joe Piscipo:4532:200:Quality Assurance

Add another entry or type EXIT to end the program.
Please enter the Department number: EXIT    5.5
newmanager: 5.5 is not a number
Please enter the Department number: EXIT
newmanager: Bye!
[tho36@hills ~]$ exit
exit

Script done on Tue 26 Nov 2013 04:47:00 PM PST
