#!/bin/bash
#
# this program asks the user to guess a number within a certain range.
# it only allows one guess and tells him whether the guess is too large
# too small, or correct.
#
# the 'secret' number and the range is contained in a datafile at
#  /pub/cs/gboyd/cs160b/labs/gnum
# with the format 
#  min max secret
# Assumptions: lots:
#   1. the file is assumed to exist and be readable
#   2. the file is assumed to contain three integers on a single
#       line with spaces as delimiters with the correct relationship
#   3. the user's input is assumed to 'look like' an integer
#
inrange() {
    # inrange is a boolean function. It takes three arguments: 
	# rangemin, rangemax and theguess, where 
	#     rangemin is the minimum value of the range and
	#     rangemax is the maximum value of the range that
	#     theguess can be in.
	#   inrange simply sets its exit status to indicate whether 
	#   theguess is between rangemin and rangemax, inclusive, or
	#   for you mathematicians, is in [rangemin,rangemax]
    # for lab4, each argument is assumed to be an integer.
    local rangemin=$1 rangemax=$2 theguess=$3 
    if echo "$theguess" | grep -vq "^[[:digit:]]\+$"; then 
        return 1
    fi
    [ "$theguess" -gt "$rangemax" ] && return 1
    [ "$theguess" -lt "$rangemin" ] && return 1
    return 0
}

# the following line reads the three values in from the file:
read min max secret < /pub/cs/gboyd/cs160b/labs/gnum

# now enter your code to:
#  1. announce the range for the guess
#  2. get the user's guess
#  3. check if it is inrange by calling the function. If it
#      is not inrange, give an error message and exit
#  4. compare the guess to the secret number, telling the user
#      whether their guess is too high, too low, or correct!

count=0
while :; do
    echo "The number is between $min and $max."
    read -p "Enter your guess:" theguess

    count=$(( count + 1 ))

#    if echo "$theguess" | grep -vq "^[[:digit:]]\+$"
#    then
#        echo "not an integer!"
#        continue
#    fi
    
    if ! inrange $min $max $theguess; then   
        echo "That's not a legal guess."  
    else
        if [ "$theguess" -lt $secret ]; then
            echo "Your guess $theguess is lower than the secret number."
        elif [ $theguess -gt $secret ]; then
            echo "Your guess $theguess is higher than the secret number."
        else
            echo "You've guessed correctly! The secret number is $secret!"
            break
        fi
    fi
done

echo "You have guessed $count times."

echo "$count $LOGNAME $(date)" >> /pub/cs/gboyd/cs160b/labs/scores

high_score=$(grep "\ $LOGNAME\ " /pub/cs/gboyd/cs160b/labs/scores | sort -n | head -n1 | cut -d' ' -f1)

echo "Your best score is $high_score!"

rank=$(cat /pub/cs/gboyd/cs160b/labs/scores | sort -n | grep -n "\ $LOGNAME\ " | head -n1 | cut -d':' -f1)

echo "Your ranking is $rank"

