#!/bin/bash
#
# this program checks a list of names to see if the user is logged on or not.
# 
error () {
    # error: output an error message and return
    # the error messages contain the program name
    # and are written to standard error

    local prog=$(basename $0)
    echo -e "$prog:ERROR: $*">&2
}

fatal() {
    # fatal: output an error message and then exit
    # the error() function is used.
    error "$*"
    # if you want to output a message about how to successfully
    # run your program (called a 'usage message'), this would
    # be the place to do it

    # now exit with an error
    exit 1
}

tmpfile=$(mktemp)

who > "$tmpfile"

while read name; do
    if ! grep -q ":$name.*:/" /etc/passwd; then
        error "no such person '$name'"
    else
       username=$(grep ":$name.*:/" /etc/passwd | cut -d: -f1)
       if grep -q "^$username " "$tmpfile"; then
           echo "$name ($username) is currently logged in"
       else
           echo "$name ($username) is not logged in"
       fi
    fi     

done < /pub/cs/gboyd/cs160b/labs/real\ names 
